### PR TITLE
Merge Feature/overview ui into Development

### PR DESCRIPTION
**Pull request by jan-vdm**

### CODE REVIEW

**Comment by jan-vdm** [comment]
> Did a smoke test, the directories need to be renamed again. If you could do that I would appreciate it :)

@IsaacZhengRenner Ummmm they seem to be fine on git and it's working for me..? Could you do a fresh pull and try again?

**Comment by IsaacZhengRenner** [comment]
@jan-vdm if you look at the repo on GitHub it has the incorrect capitalisation... but I’ll double check

**Comment by jan-vdm** [comment]
> @jan-vdm if you look at the repo on GitHub it has the incorrect capitalisation... but I’ll double check

Master has the error but not development nor the feature/overview-ui branch...

**Comment by IsaacZhengRenner** [comment]
Yeah, mb. It was screwed up on mine locally.

**Pull request merged**
